### ISSUE TITLE
BUG: No connection possible when Agent does not have camera

### ISSUE THREAD

**Issue by wardhanster** [wardhanster/blinkin-features#22]
**What happened**
No connection possible, when agent does not have a camera device.

**Desired Result**
User should connect if atleast agent has one audio device

**Comment by JokiCodes** [comment]
No Sound on user side   (microphone of agent does not get transmitted) Xiaomim MI 9 when Agent does not have camera

**Comment by wardhanster** [comment]
@kashmika ready for testing.

**Comment by kashmika** [comment]
Tested on mi note 7 everything was fine,
But When tested on Mi note  pro, and Galaxy 7 pro Toggle torch and camera switch not working.
Turn off torch button not working 
Camera switching from back to front not working.

**Comment by wardhanster** [comment]
Please create separate tickets for those devices.
