### ISSUE TITLE
BUG:Android  phone camera issue

### ISSUE THREAD

**Issue by kashmika** [wardhanster/blinkin-features#23]
Issue description
While switching the camera from front to back,  video hangs. 

Steps to reproduce the issue

1. Agent open "qa.blinkin.io" in chrome browser.
2. Scroll down "Start new call" .
3. Send sms was not working so tried to copy the link which is mention the textbox of joining link and send to customer through any medium
4. Customer got the link copied & paste it in chrome and opened.
5. Once customer gets connected agent able to see & hear from customer side.
6. Then agent tries to switch the camera from back to front video works fine but when switching again from front to back agent side video hangs and customer shows a  black color screen

What's the expected result?
Video should work fine.
Switching camera back to front & front to back should work properly .
Must be audible to both the side.
Video should not hang

What's the actual result?
Switching camera from back to front works fine, but switching again from front to back agent side video hangs but customer side a black screen
![Screenshot_2019-07-05-17-10-40-567_com android chrome 1](https://user-images.githubusercontent.com/52402647/60720582-d914ee00-9f48-11e9-858a-0c83292e53bd.png)
![Screenshot (228)](https://user-images.githubusercontent.com/52402647/60720801-80922080-9f49-11e9-8995-78039b5bc63f.png)

Network Used
Customer device: JIO
Agent side: JIO wifi

Device
Customer: Mi 7pro
Agent: HP

Webrtc test results
Open test.webrtc.org link
Tried to start
Result: Microphone not working
Tried with multiple system

**Comment by wardhanster** [comment]
@kashmika please attach a screencast.

**Comment by kashmika** [comment]
![Screenshot_(11) 1](https://user-images.githubusercontent.com/52402647/60700950-87a03b00-9f17-11e9-8eb6-b94809670a2f.png)
![Screenshot_(12) 1](https://user-images.githubusercontent.com/52402647/60700965-98e94780-9f17-11e9-9e68-0c86a57a2583.png)
![Screenshot_(13) 1](https://user-images.githubusercontent.com/52402647/60700977-a69ecd00-9f17-11e9-813e-5f81a8a9c26c.png)
![IMG-20190705-WA0011 1](https://user-images.githubusercontent.com/52402647/60701246-c84c8400-9f18-11e9-8f81-e4f1dc1284ce.jpg)

**Comment by wardhanster** [comment]
@kashmika these are screenshots - not screencasts!

**Comment by kashmika** [comment]
[Recording #2.zip](https://github.com/wardhanster/blinkin-features/files/3362116/Recording.2.zip)

**Comment by wardhanster** [comment]
Duplicte of #17
