### ISSUE TITLE
BUG: Unable to Turn off Torch on Android - mi5 & Galaxy 7Pro

### ISSUE THREAD

**Issue by kashmika** [wardhanster/blinkin-features#25]
Issue description
Torch once turn on unable to turn off  in android mi not 5 pro and samsung galaxy 7pro

Steps to reproduce the issue

Agent open "qa.blinkin.io" in chrome browser.
Scroll down "Start new call" .
Send sms was not working so tried to copy the link which is mention the textbox of joining link and send to customer through any medium
Customer got the link copied & paste it in chrome and opened.
Once customer gets connected agent able to see & hear from customer side.
Then agent tries to turn on the torch, its working but when tries to turn it off failed to turn off

What's the expected result?
Torch turn off and on should work properly

What's the actual result?
Agent  able to turn on the torch of customer ,but unable turn it off

Network Used
Customer device: JIO
Agent side: JIO wifi

Webrtc test results
Open test.webrtc.org link
Tried to start
Result: Microphone not working
Tried with multiple system

One console error occur here is the screenshot of it

![Screenshot (232)](https://user-images.githubusercontent.com/52402647/60753946-93fbc500-9ff7-11e9-8cc1-f40f1e800a55.png)

**Comment by wardhanster** [comment]
Are you able to access https://ms.blinkin.io:4443 ?
It should prompt and ask you for with username and password.
Also a `409` error is perfectly fine error

**Comment by kashmika** [comment]
Sir unable to open https://ms.blinkin.io:4443
![Screenshot (240)](https://user-images.githubusercontent.com/52402647/60861732-fe4f7800-a238-11e9-845e-8a96efa6096f.png)

**Comment by wardhanster** [comment]
Fixed in the latest release.
